### PR TITLE
Add shell version 3.22 to metadata

### PR DESCRIPTION
**Pull request by theychx**
All features tested. Please see #16

### CODE REVIEW

**Comment by luispabon** [comment]
Thank you :+1:

**Comment by luispabon** [comment]
This doesn't actually do anything for #16 though, yes?

**Comment by theychx** [comment]
No, I just discovered the problem while testing for 3.22

**Comment by luispabon** [comment]
Cheers. I'm back full on at work so not a great deal of time to investigate #16, if you can help that'd be greatly appreciated.

**Comment by skewty** [comment]
I always use alternate mode and never need to change my settings to get it to work again so that isn't it.

**Pull request merged**
